$background = rgb(272e33)
$foreground = rgb(d3c6aa)
$border_color_active = rgb(a7c080)
$accent_inactive = rgba(a7c08040)
$border_color_inactive = rgb(414b50)


# rgba versions for hyprlock compatibility
$background_rgba = rgba(39, 46, 51, 1.0)
$background_rgba_transparent = rgba(39, 46, 51, 0)
$foreground_rgba = rgba(211, 198, 170, 1.0)
$foreground_rgba_75 = rgba(211, 198, 170, 0.75)
$border_color_active_rgba = rgba(167, 192, 128, 1.0)
$border_color_inactive_rgba = rgba(65, 75, 80, 0)
$border_color_active_hex = 0xffa7c080

$accent_primary = rgba(167, 192, 128, 1.0)
$accent_error = rgba(230, 126, 128, 1.0)