$focus_opacity = 0.9
$unfocus_opacity = 0.85

# Write custom hyprland settings here, such as keyboard layouts, monitor settings, etc.

# ----------------------------------------------------- 
# Flameshot via https://github.com/flameshot-org/flameshot/issues/2978
# ----------------------------------------------------- 
windowrule = float on, match:class ^(flameshot)$
# windowrule = monitor 0,flameshot
# windowrule = move 0 0,flameshot
# windowrule = workspace 0,flameshot
windowrule = stay_focused on, match:class ^(flameshot)$
# bind = $mainMod, Print exec, XDG_CURRENT_DESKTOP=sway flameshot gui -r | wl-copy

# ----------------------------------------------------- 
## Discord
windowrule = workspace 5, match:class ^(discord)$
windowrule = opacity $focus_opacity $unfocus_opacity, match:float false, match:class ^(discord)$
windowrule = workspace 5, match:class ^(vencord)$
windowrule = opacity $focus_opacity $unfocus_opacity, match:float false, match:class ^(vencord)$
windowrule = workspace 5, match:class ^(vesktop)$
windowrule = opacity $focus_opacity $unfocus_opacity, match:float false, match:class ^(vesktop)$
# windowrule = move 1400 1800, match:class ^(discord)$
# windowrule = size 1475 1350, match:class ^(discord)$
# ----------------------------------------------------- 

# ----------------------------------------------------- 
# Startup commands
# ----------------------------------------------------- 
exec-once = xrandr --output DP-3 --primary
# exec-once = [workspace 5 silent] alacritty
exec-once = spotify
exec-once = vesktop
exec-once = [silent] piper
exec-once = zen-browser
exec-once = [silent] steam
# exec-once = [silent] lutris
# exec-once = [silent] heroic
# Focus workspaces
exec-once = hyprctl dispatch workspace 5
exec-once = hyprctl dispatch workspace 2
exec-once = hyprctl dispatch workspace 8