# Monitor (custom)
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/workspaces.conf
# Autostart
source = ~/.config/hypr/conf/autostart.conf

# Environment
source = ~/.config/hypr/conf/environment.conf

# Input (custom)
source = ~/.config/hypr/conf/custom/input.conf

# Material colors
# source = ~/.cache/material/colors-hyprland.conf
# Everforest Colors
# source = ~/.config/hypr/conf/colors/everforest.conf
# Rose Colors
source = ~/.config/hypr/conf/colors/rose.conf
source = ~/.config/hypr/conf/colors/dynamic.conf

# Some files
source = ~/.config/hypr/conf/window.conf
source = ~/.config/hypr/conf/decoration.conf
source = ~/.config/hypr/conf/layout.conf
source = ~/.config/hypr/conf/misc.conf
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/windowrule.conf

# Animations
source = ~/.config/hypr/conf/animation.conf

# Apps
source = ~/.config/hypr/conf/apps.conf

# Custom
source = ~/.config/hypr/conf/custom/general.conf

# xdg
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
