splash = false

preload = /home/johnny/wallpaper/uw-ghibli-castle.jpg


wallpaper = desc:LG Electronics LG ULTRAGEAR+ 303NTRL72662,contain:/home/johnny/wallpaper/uw-ghibli-castle.jpg
wallpaper = desc:BOE 0x0BCA,contain:/home/johnny/wallpaper/uw-ghibli-castle.jpg
wallpaper = DP-2,/home/johnny/wallpaper/uw-ghibli-castle.jpg
wallpaper = DP-3,/home/johnny/wallpaper/uw-ghibli-castle.jpg
