"""
Write waybar colors.css from pywal data so waybar uses the current theme.
Waybar style.css uses: @primary, @on_primary, @on_background, @outline_variant.
"""
import os
import logging

HOME = os.path.expanduser('~')
XDG_CONFIG_HOME = os.getenv('XDG_CONFIG_HOME', os.path.join(HOME, '.config'))
WAYBAR_COLORS_PATH = os.path.join(XDG_CONFIG_HOME, 'waybar', 'colors.css')


def _color_list(pywal_data):
    colors = pywal_data.get('colors')
    if isinstance(colors, dict):
        return [colors.get('color%i' % i, '#000000') for i in range(16)]
    return list(colors) if colors else []


def write_waybar_theme(pywal_data):
    """
    Write ~/.config/waybar/colors.css with @define-color variables
    so waybar picks up the pywal theme.
    """
    if not pywal_data:
        return
    special = pywal_data.get('special') or {}
    color_list = _color_list(pywal_data)
    if len(color_list) < 9:
        return

    background = special.get('background') or color_list[0]
    foreground = special.get('foreground') or color_list[7]
    primary = color_list[4]
    # on_primary: readable text on primary (dark if primary is light)
    on_primary = color_list[0]  # use bg as text on primary for contrast
    outline_variant = color_list[8]

    waybar_dir = os.path.dirname(WAYBAR_COLORS_PATH)
    try:
        if not os.path.isdir(waybar_dir):
            os.makedirs(waybar_dir, mode=0o755)
        with open(WAYBAR_COLORS_PATH, 'w') as f:
            f.write('/* Generated by pywalfox from pywal colors */\n')
            f.write('@define-color background %s;\n' % background)
            f.write('@define-color on_background %s;\n' % foreground)
            f.write('@define-color primary %s;\n' % primary)
            f.write('@define-color on_primary %s;\n' % on_primary)
            f.write('@define-color outline_variant %s;\n' % outline_variant)
            f.write('@define-color surface %s;\n' % background)
            f.write('@define-color surface_container %s;\n' % color_list[8])
            f.write('@define-color waybar_accent %s;\n' % primary)
            f.write('@define-color waybar_accent_fg %s;\n' % foreground)
        logging.debug('Wrote waybar theme to %s', WAYBAR_COLORS_PATH)
    except OSError as e:
        logging.warning('Could not write waybar theme: %s', e)
