"""
Write wofi theme from pywal data. Writes a single style.css with colors
inlined so wofi always loads it (avoids broken @import when style is symlinked).
"""
import os
import re
import logging

HOME = os.path.expanduser('~')
XDG_CONFIG_HOME = os.getenv('XDG_CONFIG_HOME', os.path.join(HOME, '.config'))
WOFI_DIR = os.path.join(XDG_CONFIG_HOME, 'wofi')
WOFI_STYLE_PATH = os.path.join(WOFI_DIR, 'style.css')
# Template: style with @import removed (we inject colors at top)
WOFI_TEMPLATE_PATHS = [
    os.path.join(os.getenv('DOTFILES', ''), 'wofi', 'style.css') if os.getenv('DOTFILES') else None,
    os.path.join(HOME, 'workspace', 'arch-dotfiles', 'wofi', 'style.css'),
]
# Fallback style if no template found (minimal but valid)
WOFI_FALLBACK_STYLE = '''
* { font-family: sans-serif; font-size: 14px; }
window { background-color: @background; padding: 10px; }
#input { color: @primary; background-color: @surface_container; padding: 10px; }
#text { color: @on_background; padding: 10px; }
#entry:selected { background-color: @primary; }
#entry:selected #text { color: @background; }
'''


def _get_wofi_template():
    """Load style template (without @import and color blocks) from DOTFILES or fallback path."""
    for path in WOFI_TEMPLATE_PATHS:
        if path and os.path.isfile(path):
            try:
                with open(path, 'r') as f:
                    content = f.read()
                # Remove @import and comment so we can inject colors
                content = re.sub(r'@import\s+url\s*\([^)]+\)\s*;\s*\n?', '', content)
                content = re.sub(r'/\*[^*]*Generated[^*]*\*/\s*\n?', '', content, flags=re.IGNORECASE)
                content = re.sub(r'/\*[^*]*Pywal[^*]*\*/\s*\n?', '', content, flags=re.IGNORECASE)
                # Remove any existing @define-color blocks (in case template has them)
                content = re.sub(r'@define-color\s+\w+\s+[^;]+;\s*\n+', '', content)
                return content.strip()
            except OSError:
                continue
    return WOFI_FALLBACK_STYLE.strip()


def write_wofi_theme(pywal_data):
    """
    Write ~/.config/wofi/style.css with @define-color variables inlined at the top
    and the style template below, so wofi always gets the theme (no @import needed).

    :param pywal_data dict: must have 'special' (background, foreground) and 'colors' (list or dict)
    """
    if not pywal_data:
        return
    special = pywal_data.get('special') or {}
    colors = pywal_data.get('colors')
    if isinstance(colors, dict):
        color_list = [colors.get('color%i' % i, '#000000') for i in range(16)]
    else:
        color_list = list(colors) if colors else []

    background = special.get('background') or (color_list[0] if color_list else '#1e1e1e')
    foreground = special.get('foreground') or (color_list[7] if len(color_list) > 7 else '#c5c7ca')
    primary = color_list[4] if len(color_list) > 4 else special.get('cursor', foreground)
    surface_container = color_list[8] if len(color_list) > 8 else background

    color_block = (
        '/* Generated by pywalfox from pywal colors */\n'
        '@define-color background %s;\n'
        '@define-color on_background %s;\n'
        '@define-color primary %s;\n'
        '@define-color surface_container %s;\n'
    ) % (background, foreground, primary, surface_container)

    template = _get_wofi_template()
    full_css = color_block + '\n\n' + template

    try:
        if not os.path.isdir(WOFI_DIR):
            os.makedirs(WOFI_DIR, mode=0o755)
        with open(WOFI_STYLE_PATH, 'w') as f:
            f.write(full_css)
        logging.debug('Wrote wofi style to %s', WOFI_STYLE_PATH)
    except OSError as e:
        logging.warning('Could not write wofi theme: %s', e)
