splash = false

preload = $HOME/wallpaper/uw-ghibli-castle.jpg


wallpaper = DP-1,$HOME/wallpaper/uw-ghibli-castle.jpg
wallpaper = DP-2,$HOME/wallpaper/uw-ghibli-castle.jpg
wallpaper = DP-3,$HOME/wallpaper/uw-ghibli-castle.jpg
