env = BROWSER, zen                    #! -@browser
# env = TERMINAL, alacritty             #! -@terminal
env = TERMINAL, ghostty             #! -@terminal
env = EDITOR, code                    #! -@editor
env = FILEMANAGER, nautilus           #! -@filemanager
# env = XDG_UTILS_TERMINAL, alacritty   #! -@terminal
env = XDG_UTILS_TERMINAL, ghostty   #! -@terminal
env = XDG_UTILS_BROWSER, zen          #! -@browser
env = XDG_UTILS_FILEMANAGER, nautilus #! -@filemanager
