# #171d0c, #69705c, #c5c6c2, #BA8E97, #C17E8C
$background = rgb(171d0c)
$foreground = rgb(c5c6c2)
$border_color_active = rgb(ba8e97)
$accent_inactive = rgba(ba8e9740)
$border_color_inactive = rgb(69705c)

# rgba versions for hyprlock compatibility
$background_rgba = rgba(23, 29, 12, 1.0)
$background_rgba_transparent = rgba(23, 29, 12, 0)
$foreground_rgba = rgba(197, 198, 194, 1.0)
$foreground_rgba_75 = rgba(197, 198, 194, 0.75)
$border_color_active_rgba = rgba(186, 142, 151, 1.0)
$border_color_inactive_rgba = rgba(105, 112, 92, 0)
$border_color_active_hex = 0xffba8e97

$accent_primary = rgba(186, 142, 151, 1.0)
$accent_error = rgba(193, 126, 140, 1.0)
