# #1a1f18, #68755f, #c5c7c5, #778F8A, #BF8B70
$background = rgb(1a1f18)
$foreground = rgb(c5c7c5)
$border_color_active = rgb(778f8a)
$accent_inactive = rgba(778f8a40)
$border_color_inactive = rgb(68755f)

# rgba versions for hyprlock compatibility
$background_rgba = rgba(26, 31, 24, 1.0)
$background_rgba_transparent = rgba(26, 31, 24, 0)
$foreground_rgba = rgba(197, 199, 197, 1.0)
$foreground_rgba_75 = rgba(197, 199, 197, 0.75)
$border_color_active_rgba = rgba(119, 143, 138, 1.0)
$border_color_inactive_rgba = rgba(104, 117, 95, 0)
$border_color_active_hex = 0xff778f8a

$accent_primary = rgba(119, 143, 138, 1.0)
$accent_error = rgba(191, 139, 112, 1.0)
