# #31515f, #68888f, #f4b3af, #e2787a, #c95153
$background = rgb(31515f)
$foreground = rgb(f4b3af)
$border_color_active = rgb(e2787a)
$accent_inactive = rgba(e2787a40)
$border_color_inactive = rgb(68888f)

# rgba versions for hyprlock compatibility
$background_rgba = rgba(49, 81, 95, 1.0)
$background_rgba_transparent = rgba(49, 81, 95, 0)
$foreground_rgba = rgba(244, 179, 175, 1.0)
$foreground_rgba_75 = rgba(244, 179, 175, 0.75)
$border_color_active_rgba = rgba(244, 179, 175, 1.0)
$border_color_inactive_rgba = rgba(104, 136, 143, 0)
$border_color_active_hex = 0xffe2787a

$accent_primary = rgba(226, 120, 122, 1.0)
$accent_error = rgba(201, 81, 83, 1.0)